import { Character, WorldLore } from './types';

export const WORLD_LORE: WorldLore[] = [
  {
    title: "벨크로스 제국 (Velcross Empire)",
    content: [
      "1726년, 마법과 검이 공존하는 시대.",
      "대륙의 패권을 쥐고 있는 강대국으로, 인간을 주축으로 한 문명을 이룩했습니다."
    ]
  },
  {
    title: "종족 관계 (Race Relations)",
    content: [
      "드워프: 100년 전부터 인간과 협력 관계를 맺고 기술과 자원을 교류하고 있습니다.",
      "엘프: 호전적이라는 이유로 200년 전 인간과의 전쟁 끝에 멸족에 가까운 피해를 입었습니다.",
      "몬스터: 대부분이 지성이 없는 야수에 불과하나, 일부 고지능 개체는 위협적입니다."
    ]
  }
];

export const CHARACTERS: Character[] = [
  {
    id: "ian",
    name: "이안 폰 아르젠",
    role: "황태자",
    age: "27세",
    gender: "남",
    mbti: "ENTJ",
    enneagram: "1w9, 135",
    height: "183cm",
    appearance: "금발, 벽안, 날카로운 눈매, 균형잡힌 몸",
    traits: ["완벽주의", "냉철함", "책임감"],
    description: "제국의 유일한 황태자. 흐트러진 모습을 보이지 않으며, 감정 표현이 서툴고 공적인 판단을 우선시합니다. 막중한 책임감과 압박감 속에 살고 있습니다.",
    stats: [
      { subject: '책임감', A: 25, fullMark: 30 },
      { subject: '통솔력', A: 20, fullMark: 30 },
      { subject: '냉철함', A: 20, fullMark: 30 },
      { subject: '야망', A: 15, fullMark: 30 },
      { subject: '완벽주의', A: 10, fullMark: 30 },
      { subject: '위압감', A: 5, fullMark: 30 },
    ],
    colorTheme: "amber"
  },
  {
    id: "theodore",
    name: "테오도르 폰 아르젠",
    role: "황제",
    age: "48세",
    gender: "남",
    mbti: "ESTJ",
    enneagram: "8w9, 836",
    height: "188cm",
    appearance: "금발, 벽안, 금빛 수염, 날카로운 눈매, 근육질",
    traits: ["권위적", "실리주의", "애처가"],
    description: "능력 있는 황제이자 실리주의자. 선황후를 진심으로 사랑했습니다. 황제라는 자리의 피로감을 느끼며, 귀족을 불신하고 명령조의 화법을 구사합니다.",
    stats: [
      { subject: '권위', A: 30, fullMark: 30 },
      { subject: '정치력', A: 25, fullMark: 30 },
      { subject: '현실적', A: 15, fullMark: 30 },
      { subject: '의심', A: 10, fullMark: 30 },
      { subject: '관록', A: 10, fullMark: 30 },
    ],
    colorTheme: "red"
  },
  {
    id: "kyle",
    name: "카일 로우드",
    role: "호위기사",
    age: "25세",
    gender: "남",
    mbti: "ISTJ",
    enneagram: "6w5, 614",
    height: "195cm",
    appearance: "흑발, 은안, 근육질",
    traits: ["과묵함", "충성심", "최연소 우승"],
    description: "표정 변화가 거의 없는 과묵한 호위기사. 최연소 황실 검술 대회 우승자이며, 과거 동료를 지키지 못한 죄책감과 불면증을 앓고 있습니다.",
    stats: [
      { subject: '충성심', A: 35, fullMark: 40 },
      { subject: '과묵함', A: 30, fullMark: 40 },
      { subject: '경계심', A: 20, fullMark: 40 },
      { subject: '우직함', A: 10, fullMark: 40 },
      { subject: '죄책감', A: 10, fullMark: 40 },
    ],
    colorTheme: "slate"
  },
  {
    id: "zenon",
    name: "제논 크로울리",
    role: "황실 대마법사",
    age: "24세(추정)",
    gender: "남",
    mbti: "INTP",
    enneagram: "5w4, 549",
    height: "169cm",
    appearance: "보라색 땋은 머리, 흑안, 다크서클, 여린 몸, 피어싱",
    traits: ["마법광", "히키코모리", "괴짜"],
    description: "마탑에 틀어박혀 연구만 하는 괴짜 대마법사. 사회성이 부족하고 웅얼거리듯 말하지만, 마법 이야기가 나오면 눈을 빛내며 활기를 띱니다.",
    stats: [
      { subject: '염세적', A: 25, fullMark: 30 },
      { subject: '탐구심', A: 20, fullMark: 30 },
      { subject: '회피적', A: 20, fullMark: 30 },
      { subject: '괴짜', A: 15, fullMark: 30 },
      { subject: '음침함', A: 10, fullMark: 30 },
    ],
    colorTheme: "purple"
  },
  {
    id: "lucian",
    name: "루시안 데 아르노",
    role: "사제",
    age: "21세",
    gender: "남",
    mbti: "ISFJ",
    enneagram: "9w1, 926",
    height: "178cm",
    appearance: "검고 긴 머리, 감은 눈, 입 아래 점, 잔근육",
    traits: ["성직자", "다정함", "순수함"],
    description: "누구에게나 친절하고 온화한 사제. 고아원에서 아이들을 돌보며, 세상 물정에 어둡고 모든 것을 선의로 해석하는 순진한 면이 있습니다.",
    stats: [
      { subject: '선량함', A: 30, fullMark: 30 },
      { subject: '신앙심', A: 25, fullMark: 30 },
      { subject: '순진함', A: 20, fullMark: 30 },
      { subject: '이타심', A: 10, fullMark: 30 },
      { subject: '온화함', A: 10, fullMark: 30 },
    ],
    colorTheme: "sky"
  },
  {
    id: "damian",
    name: "데미안 크로프트",
    role: "전쟁영웅 (후작)",
    age: "27세",
    gender: "남",
    mbti: "INTJ",
    enneagram: "5w6, 513",
    height: "175cm",
    appearance: "밀발, 오드아이(초/파), 얼굴 흉터, 실전 근육",
    traits: ["전쟁영웅", "평민출신", "츤데레"],
    description: "평민 출신의 전쟁 영웅이자 후작. 몸 곳곳의 흉터만큼 마음의 벽도 높습니다. 귀족 사회를 경멸하며 차가운 태도를 보이지만 의외로 단 것을 좋아합니다.",
    stats: [
      { subject: '차가움', A: 25, fullMark: 30 },
      { subject: '날카로움', A: 20, fullMark: 30 },
      { subject: '예민함', A: 20, fullMark: 30 },
      { subject: '현실감각', A: 15, fullMark: 30 },
      { subject: '절제', A: 5, fullMark: 30 },
    ],
    colorTheme: "zinc"
  },
  {
    id: "elliot",
    name: "엘리엇 하워드",
    role: "집사",
    age: "35세",
    gender: "남",
    mbti: "ISFJ",
    enneagram: "2w1, 216",
    height: "181cm",
    appearance: "단정한 흑발, 흑안, 단안경",
    traits: ["완벽함", "정보통", "헌신"],
    description: "항상 완벽한 집사. 주인의 모든 것을 꿰뚫고 있으며, 내부 정보망을 장악하고 있습니다. 예의에 어긋난 행동에는 단호하며 속으로 사람을 평가합니다.",
    stats: [
      { subject: '헌신적', A: 30, fullMark: 30 },
      { subject: '다정함', A: 20, fullMark: 30 },
      { subject: '꼼꼼함', A: 20, fullMark: 30 },
      { subject: '보수적', A: 20, fullMark: 30 },
      { subject: '걱정', A: 20, fullMark: 30 },
    ],
    colorTheme: "neutral"
  },
  {
    id: "jade",
    name: "제이드 아스카니",
    role: "거상",
    age: "26세",
    gender: "남",
    mbti: "ENFJ",
    enneagram: "3w2, 378",
    height: "186cm",
    appearance: "갈발, 흑안, 화려한 옷차림",
    traits: ["야망", "능청", "자수성가"],
    description: "대륙 상권을 장악한 자수성가 거상. 화려하고 사교적이나 속내는 계산적입니다. 명예와 지위를 갈망하며 부와 영향력을 과시하길 즐깁니다.",
    stats: [
      { subject: '야심', A: 30, fullMark: 30 },
      { subject: '계략가', A: 25, fullMark: 30 },
      { subject: '사교적', A: 15, fullMark: 30 },
      { subject: '능청', A: 10, fullMark: 30 },
      { subject: '소유욕', A: 10, fullMark: 30 },
    ],
    colorTheme: "emerald"
  },
  {
    id: "leo",
    name: "리오 폰 하트넬",
    role: "백작가 4남 (소꿉친구)",
    age: "21세",
    gender: "남",
    mbti: "ESFJ",
    enneagram: "2w1, 269",
    height: "180cm",
    appearance: "갈발, 녹안, 처진 눈매",
    traits: ["다정함", "느긋함", "편안함"],
    description: "계승 압박이 없는 백작가의 4남이자 당신의 소꿉친구. 선하고 다정하며 느긋한 성격입니다. 단 것을 매우 좋아하며 격식 없이 편안하게 다가옵니다.",
    stats: [
      { subject: '다정함', A: 30, fullMark: 30 },
      { subject: '헌신', A: 20, fullMark: 30 },
      { subject: '배려', A: 15, fullMark: 30 },
      { subject: '인내심', A: 10, fullMark: 30 },
      { subject: '선함', A: 10, fullMark: 30 },
    ],
    colorTheme: "lime"
  },
  {
    id: "silas",
    name: "사일러스 모건",
    role: "해적 선장",
    age: "42세",
    gender: "남",
    mbti: "ESTP",
    enneagram: "7w8, 783",
    height: "198cm",
    appearance: "백발, 백수염, 흑안, 위압적인 근육질",
    traits: ["쾌락주의", "잔인함", "호탕함"],
    description: "악명 높은 레드핸드 해적단의 선장. 흥미를 행동 원칙으로 삼으며, 위험을 즐기는 쾌락주의자입니다. 사실 작은 배에서는 멀미를 합니다.",
    stats: [
      { subject: '능글맞음', A: 30, fullMark: 30 },
      { subject: '쾌락주의', A: 25, fullMark: 30 },
      { subject: '기회주의', A: 15, fullMark: 30 },
      { subject: '대담함', A: 10, fullMark: 30 },
      { subject: '통찰력', A: 10, fullMark: 30 },
    ],
    colorTheme: "rose"
  },
  {
    id: "caelian",
    name: "카엘리안",
    role: "엘프 사냥꾼",
    age: "321세 (외견 23세)",
    gender: "남",
    mbti: "ISTJ",
    enneagram: "6w5, 641",
    height: "174cm",
    appearance: "은발 반묶음, 벽안, 뾰족한 귀, 슬림",
    traits: ["엘프", "까칠함", "츤데레"],
    description: "멸족당한 엘프족의 후예. 인간 문화를 저급하다 여기며 불신하지만, 인간의 음식에는 몰래 흥미를 보입니다. 숲의 규율을 중시하는 까칠한 성격입니다.",
    stats: [
      { subject: '경계심', A: 30, fullMark: 30 },
      { subject: '까칠함', A: 25, fullMark: 30 },
      { subject: '원칙주의', A: 15, fullMark: 30 },
      { subject: '섬세함', A: 10, fullMark: 30 },
      { subject: '관찰력', A: 10, fullMark: 30 },
    ],
    colorTheme: "green"
  },
  {
    id: "ethan",
    name: "에단 스펜서",
    role: "의붓형제 (공작가 양자)",
    age: "22세",
    gender: "남",
    mbti: "ISFP",
    enneagram: "4w3, 461",
    height: "182cm",
    appearance: "진한 자발, 자안, 눈 아래 점, 잔근육",
    traits: ["자격지심", "예민함", "비밀"],
    description: "몰락한 귀족 가문 출신의 공작가 양자. 낮은 자존감과 높은 자존심을 동시에 가졌으며, 동정받는 것을 극도로 싫어합니다. 글쓰기를 좋아하지만 숨깁니다.",
    stats: [
      { subject: '자격지심', A: 30, fullMark: 30 },
      { subject: '자존심', A: 25, fullMark: 30 },
      { subject: '예민함', A: 15, fullMark: 30 },
      { subject: '견제', A: 10, fullMark: 30 },
      { subject: '비관적', A: 10, fullMark: 30 },
    ],
    colorTheme: "indigo"
  }
];